# The docker image to run this CI pipeline in.
image: "binaryanalysisplatform/bap:latest"

# Run the tests
run_tests:

  tags: 
    - docker # Tag this so docker CI runners pick it up.

  only:
    # Run on main, merge requests, and any branch starting with test/*
    - main
    - merge_requests
    - /^test\/.*$/

  script:

    # Install dependencies.
    - bash -x bin/ci/exec/install-dependencies.bash

    # Source environment variables.
    - . bin/ci/lib/env.bash

    # Run the VIBES tests.
    - bash -x bin/ci/exec/run-tests.bash

    - echo "Done"
