# The docker image to run this CI pipeline in.
image: "binaryanalysisplatform/bap:latest"

# Run the tests
run_tests:

  tags: 
    - docker # Tag this so docker CI runners pick it up.

  script:

    # Install APT dependencies.
    - >-
      sudo -E apt install -y
      qemu gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi

    # Install other dependencies (non-sudo).
    - bash -x bin/setup/install-dependencies.bash

    # Source environment variables.
    - . bin/common-lib/env.bash

    # Install the vibes tool.
    - make

    # Run the various tests.
    - bash -x bin/unit-tests/run-tests.bash --report-results
    - bash -x bin/integration-tests/run-tests.bash --report-results
    - bash -x bin/system-tests/exec/run-tests.bash --report-results

    - echo "Done"
