# The docker image to run this CI pipeline in.
image: "binaryanalysisplatform/bap:latest"

# Some variables for use
variables:
  XDG_HOME: ~
  MINIZINC_URL: https://github.com/MiniZinc/MiniZincIDE/releases/download/2.5.3/MiniZincIDE-2.5.3-bundle-linux-x86_64.tgz
  MINIZINC_INSTALL_DIR: ~/MiniZincIDE-2.5.3-bundle-linux-x86_64/

# Run the tests
run_tests:

  tags: 
    - docker # Tag this so docker CI runners pick it up.

  script:

    # Install bap_wp.
    - cd ${XDG_home}
    - git clone https://github.com/draperlaboratory/cbat_tools.git
    - pushd cbat_tools/wp/lib/bap_wp
    - make
    - cd ${CI_PROJECT_DIR}

    # Install minizinc.
    - cd ${XDG_home}
    - curl -L ${MINIZINC_INSTALL} --output minizinc.tgz
    - tar zxvf minizinc.tgz
    - ls -la
    - echo "PATH :=> ${PATH}" 
    - export PATH=${MINIZINC_INSTALL_DIR}/bin:${PATH}
    - export LD_LIBRARY_PATH=${MINIZINC_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
    - echo ${PATH}
    - echo ${LD_LIBRARY_PATH}
    - cd ${CI_PROJECT_DIR}

    # Install dependencies
    - opam install -y ounit2 ppx_deriving_yojson

    # Run the VIBES tests.
    - bash -x bin/ci/run-tests.bash

    # Run simple-compiled
    - rm -rf resources/simple-compiled/main.patched
    - make main.patched -C resources/simple-compiled/ 

    - echo "Done"
