# The docker image to run this CI pipeline in.
image: "binaryanalysisplatform/bap:latest"

# Run the tests
run_tests:

  tags: 
    - docker # Tag this so docker CI runners pick it up.

  script:

    # Install dependencies and install the VIBES tool.
    - bash -x bin/setup/ubuntu.bash --report-results
    - source bin/setup/env.bash
    - make

    # Run the various tests.
    - bash -x bin/unit-tests/run-tests.bash --report-results
    - bash -x bin/integration-tests/run-tests.bash --report-results
    - bash -x bin/system-tests/run-tests.bash --report-results

    - echo "Done"
